// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: f24f49788f0b52f34ebd88faf79717b8ea76952f1761d481f3fcf41463012765

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "acme-theme";

export const themeNames: ThemeName[] = ["acme-theme"];

export type KcEnvName =
    | "SHADCN_THEME_LOGO_WHITE_URL"
    | "SHADCN_THEME_LOGO_DARK_URL"
    | "SHADCN_THEME_LAYOUT"
    | "SHADCN_THEME_SIDE_IMAGE_URL"
    | "SHADCN_THEME_PRESET"
    | "SHADCN_THEME_BASE"
    | "SHADCN_THEME_RADIUS"
    | "SHADCN_THEME_FONT"
    | "SHADCN_THEME_PLACEHOLDER";

export const kcEnvNames: KcEnvName[] = [
    "SHADCN_THEME_LOGO_WHITE_URL",
    "SHADCN_THEME_LOGO_DARK_URL",
    "SHADCN_THEME_LAYOUT",
    "SHADCN_THEME_SIDE_IMAGE_URL",
    "SHADCN_THEME_PRESET",
    "SHADCN_THEME_BASE",
    "SHADCN_THEME_RADIUS",
    "SHADCN_THEME_FONT",
    "SHADCN_THEME_PLACEHOLDER"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    SHADCN_THEME_LOGO_WHITE_URL: "",
    SHADCN_THEME_LOGO_DARK_URL: "",
    SHADCN_THEME_LAYOUT: "two-column",
    SHADCN_THEME_SIDE_IMAGE_URL: "",
    SHADCN_THEME_PRESET: "neutral",
    SHADCN_THEME_BASE: "neutral",
    SHADCN_THEME_RADIUS: "default",
    SHADCN_THEME_FONT: "geist",
    SHADCN_THEME_PLACEHOLDER: "true"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
